baseURL = 'https://Twowra.github.io/'
languageCode = 'zh-cn'
title = '大笨蛋的博客'
theme = 'stack'

[params]
mainSections = ['post']

[params.sidebar]
emoji = '😚'
subtitle = '动画爱好者，时不时发一些技术学习内容喵'

[params.article]
math = false
toc = true

[params.comments]
enabled = true
provider = 'giscus'

[params.comments.giscus]
repo = 'Twowra/Twowra.github.io'
repoID = 'R_kgDOUSI2jA'
category = 'Announcements'
categoryID = 'DIC_kwDOUSI2jM4DFIwP'
mapping = 'pathname'
lightTheme = 'github_light'
darkTheme = 'github_dark'
